"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Segurança
SECRET_KEY = 'django-insecure-d8h-2ri4d@ya%^ui#pmyod_&c_8-c2lflx!qs5r5fd1(&5^p6s'
DEBUG = True
ALLOWED_HOSTS = ["*"]  # libera tudo em ambiente de dev

# ======================================
# APLICAÇÕES INSTALADAS
# ======================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceiros
    'rest_framework',
    'corsheaders',

    # Apps locais
    'eventos_app',  # mudou de 'eventos' pra 'eventos_app'
]

# ======================================
# MIDDLEWARE
# ======================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Adiciona CORS antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ======================================
# CONFIGURAÇÕES DE CORS
# ======================================

CORS_ALLOW_ALL_ORIGINS = True  # libera requisições de qualquer origem (para o front Vue)
CORS_ALLOW_CREDENTIALS = True

# ======================================
# REST FRAMEWORK
# ======================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# ======================================
# URLS E TEMPLATES
# ======================================

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# ======================================
# BANCO DE DADOS (SQLite por padrão)
# ======================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ======================================
# VALIDAÇÃO DE SENHAS
# ======================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ======================================
# LOCALIZAÇÃO / LINGUAGEM
# ======================================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Brasilia'
USE_I18N = True
USE_TZ = True

# ======================================
# ARQUIVOS ESTÁTICOS
# ======================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ======================================
# CONFIG PADRÃO DE CHAVE PRIMÁRIA
# ======================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
